spring:

  main:
    allow-circular-references: true

  jpa:
    show-sql: true
    database: postgresql
    defer-datasource-initialization: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://ec2-54-225-234-165.compute-1.amazonaws.com/dfn1p4u7bcemia
    username: pqqmerssjhgyqb
    password: 46e1d8e03b324b4c9e8eba779839793af08da2d56065b4f2d73c1b0741161bc0
    driver-class-name: org.postgresql.Driver

  redis:
    url: redis://:p8c90a3e176486a4e393032ccf5e4e061937f1607e4843d1890911a11cecec48f@ec2-44-212-171-11.compute-1.amazonaws.com:26849

jwt:
  secret-key: rkskekfkfkhx;skjh#@&$*LGhsdlgh;z&*@!#*(@ldsgkhsdg;slj
  token:
    expired-time-ms: 2592000000 # 30일
